let formEl = document.getElementById('currForm')
let inputEl = document.getElementById('currInput')
let convertBtn = document.getElementById('convertButton')
let clearBtn = document.getElementById('clearButton')
let dropdownEl =  document.getElementById('dropdown')